
## REACT: change the build directory to be within react's scope
# project_structure:
#    build: client/src/artifacts

# automatically fetch contract sources from Etherscan
autofetch_sources: True
dotenv: .env
token:
  name: ${NAME}
  symbol: ${SYMBOL}
  decimals: ${DECIMALS} 
  mint_cost: ${MINT_COST} 
  max_supply: ${MAX_SUPPLY} 
dependencies:
  - OpenZeppelin/openzeppelin-contracts@2.5.0
  - OpenZeppelin/openzeppelin-contracts@4.4.1
compiler:
    solc:
        remappings:
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@2.5.0"
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1"
networks:
  default: development
  development:
    verify: False
    update_interval: 60
  ganache-local:
    verify: False
    update_interval: 60
  rinkeby:
    verify: True
    update_interval: 60
  kovan:
    verify: True
    update_interval: 60
wallets:
  from_key: ${PRIVATE_KEY}
# enable output of development artifacts to load with react
dev_deployment_artifacts: true